### ISSUE TITLE
New sample size for different fight outcomes

### ISSUE THREAD

**Issue by latrodektus** [latrodektus/UFC-Beard-Data#10]
Hey Will,
Since we added the 2 extra individuals (because of fixing the data sheet). We now have two fights unaccounted for in this list
KO = 83
TKO = 117
injury = 7
submissions = 97
judge decisions = 277
disqualification or no contest judgement = 17

Can you give me a frequency distribution?

**Comment by wcornwell** [comment]
Var1 | Freq
-- | --
KO | 83
No contest/draw/disqualification/injury | 17
Split decision | 52
Stoppage (doctor/corner) | 7
Submission | 98
TKO | 118
Unanimous decision | 225

**Comment by latrodektus** [comment]
Bewdy
