### ISSUE TITLE
Report the random effects structure

### ISSUE THREAD

**Issue by latrodektus** [latrodektus/UFC-Beard-Data#2]
From what I do understand of the Bradley-Terry model is that variance due to non-independence of observations is accounted for via random effects. If this is the case, the authors should report the random effects structure. The random effects should also be reported, at least in the supplementary materials. This information will give an indication of how well the model fits the data.

**Comment by wcornwell** [comment]
If I understand what they want, I think this might already be here (if you scroll down): https://github.com/latrodektus/UFC-Beard-Data 

I guess we'll want to turn that document into some kind of supplementary material?  Any special journal rules for supplementary materials?

**Comment by latrodektus** [comment]
Yeah, the random effects are there already. I thought they would be. Sorry.
I can add that stuff to the text next week.
