### ISSUE TITLE
Power analysis or Simulation

### ISSUE THREAD

**Issue by latrodektus** [latrodektus/UFC-Beard-Data#3]
Part of the conclusion relies on the data being able to detect an effect if one exists; the manuscript would be improved if it included some sort of power analysis or simulation to show that this is the case. This would strengthen the conclusion that beardedness does not influence fighting outcomes

**Comment by wcornwell** [comment]
This the hardest one, but possibly doable.  The question is what is how to simulate data in which beardedness has different size effects.  This is pretty easy in simpler models but for this one, it's a bit tricky because the response variable is more complicated than the standard continuous normally distributed thing.  

The model looks for effect of beardedness on BT abilities, but it's hard to think about how that effect would be put into understandable units.  The standard form would be that beards increase Y by X%.  The question is what is Y.  

Any idea @latrodektus ?

**Comment by BarnabyDixson** [comment]
Hey what's BT abilities again?

**Comment by latrodektus** [comment]
BT abilities is the ability score that the model gives each player based on their contest outcomes and who those contests were against. It's as if they lined up all the participants from best to worst (or vice versa), but using contest outcomes and competitors as the objective measure (since those are the most reliable data).

**Comment by latrodektus** [comment]
now that you put it that way @wcornwell, it is harder to think about. 

Could we randomly assign beard values to all the players and see how that affects their BT abilities? Then maybe bootstrap this several times and see if that changes anything -- and then compare our answer to what we have with the real data?

**Comment by BarnabyDixson** [comment]
This sounds like a way to go about it and answers the reviewers questions, I reckon. Is it possible to do this?

**Comment by wcornwell** [comment]
Yes that's the first step, but then we'd have to 

1. systematically assign bearded competitors a higher ability, 

2. simulate the fights, 

3. Run our model

4. Repeat with different amounts of difference between beard and non beard.

5. Report the level of difference when we statistically detect the effect

Make sense?

**Comment by BarnabyDixson** [comment]
Hey Will,

This makes sense to me! I just lack the skills to any of the stats....... sorry! Are you and Mike OK to have a crack at this?

Thanks mate!

**Comment by wcornwell** [comment]
yeah, we're making progress...I feel like this is what the editor wants:

![img_20170930_101703](https://user-images.githubusercontent.com/5534161/31041306-407309d8-a5d6-11e7-8bdf-9d7b36066616.jpg)

I think we can sort it out next week

**Comment by wcornwell** [comment]
![power_analysis](https://user-images.githubusercontent.com/5534161/31264846-4be3ea86-aab7-11e7-804f-6c7ca5a6d48b.png)

**Comment by wcornwell** [comment]
The observed proportion of wins by bearded competitors was 49.3 % .  We would have detected a significant effect at 58 % (on average) suggesting that that our method and sample size had sufficient power to detect a reasonable sized competitive advantage--if it had existed.  

The fact that at this sample size the proportion of victories by bearded competitors is so close to 50% suggests that any effect of beards on competitive outcomes, if it exists at all, is vanishing small.
