### ISSUE TITLE
Average fights per fighter

### ISSUE THREAD

**Issue by latrodektus** [latrodektus/UFC-Beard-Data#5]
What was the average number of fights per fighter in the dataset?

Maybe also the distribution? I don't know, should this be a figure in the supplemental? (Maybe depending on the range)

**Comment by wcornwell** [comment]
![image](https://user-images.githubusercontent.com/5534161/31207611-11750c32-a9cb-11e7-928d-3ea240860d47.png)

**Comment by latrodektus** [comment]
Hey @wcornwell, is it simple enough to also get a mean and se?

**Comment by wcornwell** [comment]
se is a bit weird on such right-skewed data but mean and median are ok

```
[1] "median number of fights was 2"
[1] "mean number of fights was 3.0379746835443"
```
