### ISSUE TITLE
Within individual comparison

### ISSUE THREAD

**Issue by latrodektus** [latrodektus/UFC-Beard-Data#7]
Maybe won't be able to check because of power, but putting this in here just in case:

If men with “weaker jaws” are more likely to wear beards, then a protective effect may not be apparent in between-subjects analyses. Within-subjects comparisons are necessary. Does the Bradley-Terry Model allow one to test between- and within-subjects effects separately? This was not clear from the manuscript, but within-subject comparisons (same fighter with and without beard) are most relevant.

Beards may function in intimidation. If so, inferior fighters may perceive a greater benefit to intimidating, and if intimidation helps win (rather than just avoid) fights, then again the effect of beards on fighting success may be invisible in between-subjects analyses. A strong test of this would be whether the same men are more likely to win fights with a beard vs. without.

**Comment by latrodektus** [comment]
and also this comment:

“the ‘beard’ category included the percentage of men with trimmed and bushy full beards…”  However, if as the authors state, “facial hair might reflect a handicap in fights that allow opponents to grasp and pull a fighter towards an opponent towards them [sic]”, then only a full beard long enough to grasp would be relevant in test this possibility. Thus, this particular handicap hypothesis should be tested as full beard vs. all else. And here, the prediction would be that the same fighter would be less likely to win when wearing a beard. However, is there any anecdotal evidence that beard-grabbing occurs with any frequency? This seems doubtful.

**Comment by wcornwell** [comment]
I'm 98% sure this one is not possible, due to sample size issues

**Comment by latrodektus** [comment]
Okay. Let's just leave this one out then.
