### ISSUE TITLE
Re-write stats analysis section of methods to reflect new analyses

### ISSUE THREAD

**Issue by wcornwell** [latrodektus/UFC-Beard-Data#8]
Tentatively we'll have:

1. Analysis of winning and losing with three levels of facial hair MAIN TEXT BUT SLIGHTLY CHANGED

2. Analysis of winning and losing with two levels of facial hair (lumping clean shaven and other facial hair together) SUPPLEMENTAL TABLE

3. Analysis of only KO and TKO with three levels of facial hair MAIN TEXT BUT CHANGED

4. Analysis of only KO and TKO with two levels of facial hair (lumping clean shaven and other facial hair together) SUPPLEMENTAL TABLE

5. A power analysis based on a randomization of the analysis in (2) NEW FIGURE

We also have to explain and justify the potential predictors considered.  Right now it's (a) previous, (b) facial hair, (c) height, (d) reach, (e) stance.

**Comment by wcornwell** [comment]
look ok to you @BarnabyDixson ?

**Comment by BarnabyDixson** [comment]
Looks good to me! Thanks Will.....

**Comment by wcornwell** [comment]
@BarnabyDixson @latrodektus  cool!  All the results are now [here](https://github.com/latrodektus/UFC-Beard-Data), i think let me know if you have any questions

**Comment by wcornwell** [comment]
@latrodektus you're probably on this already, but just remember to delete that part in the methods about the two missing data points--they are all in there now.
